### ISSUE TITLE
你好，能否将KLineChartAdapter中的datas和points改成protected，这样就方便扩展

### ISSUE THREAD

**Issue by leguang** [icechao/KlineChart#10]
你好，能否将KLineChartAdapter中的datas和points改成protected，这样就方便扩展
比如我现在要完成一个加载更多的功能，即第一次请求为1000条，当向右滑动，到达最左边的时候，就触发加载更多，又拿到1000条加载到data的第0位，此时你的points我拿不到，不能重置它，因为我看到你代码里都做了如下操作：
```
points = DataTools.calculate(datas);
```
虽然我暂时不是很清楚这是干什么，但是我无法扩展了

**Comment by icechao** [comment]
> 你好，能否将KLineChartAdapter中的datas和points改成protected，这样就方便扩展
> 比如我现在要完成一个加载更多的功能，即第一次请求为1000条，当向右滑动，到达最左边的时候，就触发加载更多，又拿到1000条加载到data的第0位，此时你的points我拿不到，不能重置它，因为我看到你代码里都做了如下操作：
> 
> ```
> points = DataTools.calculate(datas);
> ```
> 
> 虽然我暂时不是很清楚这是干什么，但是我无法扩展了

这个是对数据 的加工~   
因为计算需要从第一个开始~   这个方法会把数据加工成数据buffer 
所以你要加载更多只需要调用adater的resetData 不需要对数据加载进行处理

**Comment by leguang** [comment]
赞，辛苦了
