### ISSUE TITLE
你好，打扰阁下了，关于加载更多的问题

### ISSUE THREAD

**Issue by leguang** [icechao/KlineChart#11]
你好，打扰阁下了，关于加载更多的问题
当加载1000条，滑动到最左边的时候，再加载1000条，此时adapter里我写了个方法，就是将新来的这1000条加载在list头部：
```
datas.addAll(0, data);
points = DataTools.calculate(datas);
```
然后刷新：
```
notifyDataSetChanged();
```
虽然K线是刷新了，但是停留在最左边，也就是新来的1000+原先的1000条，总共2000条数据的最左边，此时只要手指稍稍向右滑动一下就触发onSlidLeft方法了。
按道理应该是新加载的这1000条数据应该是在屏幕外，我还可以继续向右滑动，直到我滑完了这新的1000条，滑到最左边再触发onSlidLeft的。请问是不是有什么法子可以实现这种效果？

**Comment by icechao** [comment]
> 右滑动，直到我滑完

#

在触发一次滑动事件后后强制结束滑动事件 @

**Comment by leguang** [comment]
赞，辛苦了

**Comment by icechao** [comment]
已无此问题
