### ISSUE TITLE
关于点击显示十字线的问题

### ISSUE THREAD

**Issue by czgenymotion** [icechao/KlineChart#17]
1、十字线方法setSelectedShowCrossPoint被设置为私有，我无法使用取消十字线交点原点显示
2、点击显示十字线以后再拖动视图，发现十字线没有隐藏，无法拖动试图

**Comment by icechao** [comment]
> 1、十字线方法setSelectedShowCrossPoint被设置为私有，我无法使用取消十字线交点原点显示
> 2、点击显示十字线以后再拖动视图，发现十字线没有隐藏，无法拖动试图

1.在在属性文件中配置,抱歉后面会修改为public,现在可以使用属性配置
2.要设置点击的模式

**Comment by icechao** [comment]
已修改
