### ISSUE TITLE
属性设置的访问性建议

### ISSUE THREAD

**Issue by burgessjp** [icechao/KlineChart#19]
建议把目前的一些 `private` 的属性设置方法更改为 `public`，方便代码调用。

![image](https://user-images.githubusercontent.com/10663475/84586973-0737c900-ae4e-11ea-9e83-440813d973e7.png)
附带提一个bug，这里应该是 `getDimension` 不是 `getInt`

**Comment by icechao** [comment]
> 建议把目前的一些 `private` 的属性设置方法更改为 `public`，方便代码调用。
> 
> ![image](https://user-images.githubusercontent.com/10663475/84586973-0737c900-ae4e-11ea-9e83-440813d973e7.png)
> 附带提一个bug，这里应该是 `getDimension` 不是 `getInt`

已修改,

**Comment by burgessjp** [comment]
👍
