### ISSUE TITLE
有没有选择默认显示哪一要k线的方法

### ISSUE THREAD

**Issue by xiongxiangdong** [icechao/KlineChart#2]
如果滑动到最左边,有什么方法滑动回最右边?

**Comment by icechao** [comment]
> 如果滑动到最左边,有什么方法滑动回最右边?

K线的View调用这个方法

   public void setResetTranslate(boolean resetTranslate) {
        this.resetTranslate = resetTranslate;
    }

**Comment by xiongxiangdong** [comment]
谢谢作者回答了．调用这个方法还要notifyChanged一下．
