### ISSUE TITLE
Kline 更新数据问题

### ISSUE THREAD

**Issue by lvfaqiang** [icechao/KlineChart#22]
刷新数据时，和上一组数据值相差太大的情况下，出现最后一个数据柱子拉的很长。

比如我当前数据的范围时  10000 - 20000，  刷新切换数据为 100-200 ，切换后，最后一个条形柱拉长，然后再缩回来。

**Comment by icechao** [comment]
后期版本修复 ,  这个问题在重置数据前   先resetData一个空集合进去 暂时解决问题
