### ISSUE TITLE
如何滑动加载更多

### ISSUE THREAD

**Issue by jiegege10** [icechao/KlineChart#23]
调用onSlidLeft监听会多次触发请求。
大佬，有其他的方法吗？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by icechao** [comment]
> 调用onSlidLeft监听会多次触发请求。
> 大佬，有其他的方法吗？
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

使用的那个版本

**Comment by icechao** [comment]
> 有其他的方法吗？

1. 使用2.0.5版本 不要使用源码 
2. 自己加下判断

**Comment by icechao** [comment]
[commit[](https://github.com/icechao/KlineChart/commit/7a5ef18b94179b0539edba7418471841432f8327)]

**Comment by icechao** [comment]
[https://github.com/icechao/KlineChart/commit/9eea41db9d4ca981d055e071790960860dd8f81a](https://github.com/icechao/KlineChart/commit/9eea41db9d4ca981d055e071790960860dd8f81a)
