### ISSUE TITLE
怎么隐藏交易量的图？

### ISSUE THREAD

**Issue by ted23335921** [icechao/KlineChart#4]
怎么隐藏交易量的图？

**Comment by icechao** [comment]
新加方法 : 
     
public void setChartChildState(Status.ChildStatus state) 
        参数
        Status.ChildStatus.MAIN_ONLY         :只显示主图
        Status.ChildStatus.MAIN_VOL          :显示主图量视图  默认值
        Status.ChildStatus.MAIN_INDEX        :主图指标图
        Status.ChildStatus.MAIN_VOL_INDEX(3) :主图交易量指标图
