### ISSUE TITLE
MACD,OBV,KDJ,BOLL,RSI 的算法能分享一下吗？

### ISSUE THREAD

**Issue by imobject** [icechao/KlineChart#5]
MACD,OBV,KDJ,BOLL,RSI 的算法能分享一下吗？

**Comment by icechao** [comment]
> CD,OBV,KDJ,BOLL,RSI 的算法能分

Rsi  boll   macd 算法可在   DataHelper 查看 ,  至于kdj  我是用的  百科上面写的

**Comment by imobject** [comment]
非常感谢



在 2019-08-14 09:40:09，"ice" <notifications@github.com> 写道：


CD,OBV,KDJ,BOLL,RSI 的算法能分

Rsi boll macd 算法可在 DataHelper 查看 , 至于kdj 我是用的 百科上面写的

**Comment by zhang6321615** [comment]
会考虑增加 EMA 么？
