### ISSUE TITLE
你好，非常感谢阁下的这个项目，基于这套K线方案，阁下定制是最完善的，请问能否留个联系方式？阁下是否愿意接受付费定制？

### ISSUE THREAD

**Issue by leguang** [icechao/KlineChart#8]
你好，非常感谢阁下的这个项目，基于这套K线方案，阁下定制是最完善的，请问能否留个联系方式？阁下是否愿意接受付费定制？

**Comment by icechao** [comment]
> 下定制是最完善的，请问能否留个联系方

QQ : 499849211
