### ISSUE TITLE
刚下载好了跑了一下，当鼠标向右拖动时报错

### ISSUE THREAD

**Issue by leguang** [icechao/KlineChart#9]
![image](https://user-images.githubusercontent.com/12870924/64071825-285f6c80-ccb5-11e9-9f54-89ccadff9cbb.png)
![image](https://user-images.githubusercontent.com/12870924/64071827-390fe280-ccb5-11e9-813e-2a103f51209d.png)

**Comment by icechao** [comment]
抱歉 这个应该是对集合数据
应该是在滑动到最左边时修改数据同时更新了K线信息  
出现 了并发修改异常是我的demo数据处理有问题  
我后面优化
